[[services]]
name = "api"

[services.build]
builder = "dockerfile"
dockerfilePath = "apps/api/Dockerfile"

[services.deploy]
healthcheckPath = "/health"
healthcheckTimeout = 120
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[[services]]
name = "@patelrep/web"

[services.build]
builder = "dockerfile"
dockerfilePath = "apps/web/Dockerfile"

[services.deploy]
startCommand = "node server.js"
healthcheckPath = "/"
healthcheckTimeout = 120
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
