import Link from 'next/link'
import { ArrowRight, BellRing, Check, ClipboardCheck, Clock3, Sparkles, Wrench } from 'lucide-react'

const workflows = [
  { icon: ClipboardCheck, eyebrow: 'Housekeeping', title: 'Every room has one clear next step.', copy: 'Turn a shifting room list into an easy, live board your supervisors and housekeepers can trust.', detail: 'Ready rooms, inspections, late checkouts', tone: 'bg-ready-soft text-ready border-ready-line' },
  { icon: Wrench, eyebrow: 'Engineering', title: 'Keep small problems from becoming out-of-order rooms.', copy: 'Give engineers a clean queue, the right context, and a shared record of what was fixed.', detail: 'Work orders, preventive maintenance, assets', tone: 'bg-info-soft text-info border-info-line' },
  { icon: Sparkles, eyebrow: 'AI copilot', title: 'A quiet second supervisor for every shift.', copy: 'Spot risks, turn plain-language notes into tasks, and keep the team focused on guests—not software.', detail: 'Shift briefings, task capture, service recovery', tone: 'bg-ai-soft text-ai border-ai-line' },
]

export default function RootPage() {
  return <main className="min-h-screen overflow-hidden bg-paper text-ink">
    <section className="relative isolate overflow-hidden bg-[#1a1815] text-paper">
      <div className="pointer-events-none absolute inset-x-0 top-0 h-[34rem] bg-[radial-gradient(circle_at_82%_18%,rgba(184,67,28,0.35),transparent_28%),radial-gradient(circle_at_66%_78%,rgba(12,110,99,0.25),transparent_26%)]" />
      <div className="relative mx-auto max-w-7xl px-6 pb-16 pt-5 sm:px-10 lg:px-12 lg:pb-24">
        <header className="flex items-center justify-between gap-4">
          <Link href="/" className="flex items-center gap-2.5 text-sm font-semibold tracking-tight" aria-label="PatelRep home"><span className="grid size-8 place-items-center rounded-[10px] bg-accent font-mono text-base text-white">✦</span><span>PatelRep</span></Link>
          <nav className="hidden items-center gap-7 text-sm text-[#c5beaf] md:flex" aria-label="Primary navigation"><a className="transition hover:text-white" href="#workflows">Workflows</a><a className="transition hover:text-white" href="#for-hotels">For hotels</a><a className="transition hover:text-white" href="#pricing">Pricing</a></nav>
          <Link href="/login" className="inline-flex min-h-10 items-center justify-center rounded-lg border border-[#4a4640] px-4 text-sm font-medium text-paper transition hover:border-[#807a70] hover:bg-white/5">Sign in</Link>
        </header>

        <div className="grid gap-12 pb-8 pt-16 lg:grid-cols-[minmax(0,0.95fr)_minmax(30rem,1.05fr)] lg:items-center lg:pt-24">
          <div className="max-w-2xl">
            <p className="mb-6 inline-flex items-center gap-2 rounded-full border border-white/15 bg-white/5 px-3 py-1.5 font-mono text-[11px] font-medium uppercase tracking-[0.14em] text-[#d8e6f0]"><span className="size-1.5 rounded-full bg-[#4ab8a8]" />Built for 50–150 room Texas hotels</p>
            <h1 className="max-w-xl font-display text-5xl leading-[0.95] tracking-[-0.045em] text-white sm:text-6xl lg:text-7xl">Hotel operations,<br />finally <em className="text-[#f2b59d]">in sync.</em></h1>
            <p className="mt-7 max-w-lg text-lg leading-8 text-[#c5beaf]">PatelRep gives your floor team one calm, shared view of rooms, repairs, requests, and the work that matters next.</p>
            <div className="mt-9 flex flex-wrap gap-3"><Link href="/login" className="inline-flex min-h-12 items-center gap-2 rounded-lg bg-accent px-5 text-sm font-semibold text-white shadow-[0_12px_28px_rgba(184,67,28,0.25)] transition hover:bg-[#cb542b] focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-white">Start a pilot <ArrowRight className="size-4" aria-hidden="true" /></Link><a href="#workflows" className="inline-flex min-h-12 items-center gap-2 rounded-lg px-5 text-sm font-semibold text-white transition hover:bg-white/10">See how it works <ArrowRight className="size-4" aria-hidden="true" /></a></div>
            <div className="mt-10 flex flex-wrap gap-x-6 gap-y-3 text-sm text-[#c5beaf]">{['No hardware to buy', 'Mobile-first for the floor', 'Set up in one shift'].map((item) => <span key={item} className="flex items-center gap-2"><Check className="size-4 text-[#4ab8a8]" aria-hidden="true" />{item}</span>)}</div>
          </div>

          <div className="relative mx-auto w-full max-w-2xl lg:ml-auto"><div className="absolute -inset-4 rounded-[2rem] bg-[#d97757]/10 blur-2xl" /><div className="relative overflow-hidden rounded-2xl border border-white/10 bg-[#f7f4ee] p-3 shadow-2xl shadow-black/35 sm:p-4"><div className="overflow-hidden rounded-xl border border-[#e6dfd1] bg-white">
            <div className="flex items-center justify-between border-b border-[#e6dfd1] px-4 py-3 sm:px-5"><div><p className="font-mono text-[10px] font-semibold uppercase tracking-[0.12em] text-ink-3">Today · Tuesday</p><p className="mt-0.5 text-sm font-semibold text-ink">Lone Star Inn · Austin</p></div><span className="inline-flex items-center gap-1.5 rounded-full bg-ready-soft px-2.5 py-1 text-xs font-semibold text-ready"><span className="size-1.5 rounded-full bg-ready" />Floor on track</span></div>
            <div className="grid gap-3 p-3 sm:grid-cols-[1.32fr_0.88fr] sm:p-4"><section className="rounded-lg border border-line bg-surface-2 p-3.5" aria-label="Room readiness overview"><div className="flex items-center justify-between"><p className="font-mono text-[10px] font-semibold uppercase tracking-[0.12em] text-ink-3">Room readiness</p><span className="text-xs font-semibold text-ready">52 / 87 ready</span></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-surface-3"><div className="h-full w-[60%] rounded-full bg-ready" /></div><div className="mt-4 grid grid-cols-4 gap-1.5" aria-label="Room status sample">{['bg-ready', 'bg-ready', 'bg-info', 'bg-progress', 'bg-alert', 'bg-ready', 'bg-info', 'bg-ready', 'bg-progress', 'bg-ready', 'bg-alert', 'bg-info'].map((color, index) => <span key={index} className={`h-7 rounded-[5px] ${color}`} />)}</div><div className="mt-3 flex items-center justify-between text-[11px] text-ink-3"><span>6 inspections waiting</span><span>3 late checkouts</span></div></section><section className="rounded-lg border border-line bg-[#1a1815] p-3.5 text-paper" aria-label="AI shift brief"><div className="flex items-center gap-2 text-[#f2b59d]"><Sparkles className="size-3.5" aria-hidden="true" /><p className="font-mono text-[10px] font-semibold uppercase tracking-[0.12em]">Shift brief</p></div><p className="mt-3 text-sm font-semibold leading-5">Room 214 needs a fast check before the 1:00 PM arrival.</p><p className="mt-2 text-xs leading-4 text-[#c5beaf]">One open maintenance task and a checkout waiting for inspection.</p><span className="mt-4 inline-flex min-h-8 items-center gap-1.5 rounded-md bg-white/10 px-2.5 text-xs font-semibold">Review room <ArrowRight className="size-3" aria-hidden="true" /></span></section></div>
            <div className="grid border-t border-[#e6dfd1] sm:grid-cols-3">{[['24m', 'average clean'], ['6', 'open work orders'], ['3', 'VIP arrivals']].map(([value, label]) => <div key={label} className="border-[#e6dfd1] px-4 py-3 text-center not-last:border-b sm:not-last:border-b-0 sm:not-last:border-r"><p className="font-display text-2xl leading-none text-ink">{value}</p><p className="mt-1 text-[10px] font-medium uppercase tracking-[0.1em] text-ink-3">{label}</p></div>)}</div>
          </div></div></div>
        </div>
      </div>
    </section>

    <section id="for-hotels" className="border-b border-line bg-surface px-6 py-8 sm:px-10 lg:px-12"><div className="mx-auto flex max-w-7xl flex-col gap-5 md:flex-row md:items-center md:justify-between"><p className="max-w-xl font-display text-2xl leading-tight text-ink sm:text-3xl">The work moves fast. Your operations system should make the next right action obvious.</p><div className="grid grid-cols-3 divide-x divide-line rounded-xl border border-line bg-surface-2 text-center">{[['1', 'shared board'], ['3', 'connected teams'], ['0', 'extra clipboards']].map(([number, label]) => <div key={label} className="px-4 py-3 sm:px-6"><p className="font-display text-3xl leading-none text-accent">{number}</p><p className="mt-1 text-[10px] font-semibold uppercase tracking-[0.08em] text-ink-3">{label}</p></div>)}</div></div></section>

    <section id="workflows" className="mx-auto max-w-7xl px-6 py-20 sm:px-10 lg:px-12 lg:py-28"><div className="max-w-2xl"><p className="font-mono text-[11px] font-semibold uppercase tracking-[0.14em] text-accent">Built around the floor</p><h2 className="mt-4 font-display text-4xl leading-[1.02] tracking-[-0.035em] text-ink sm:text-5xl">Less hunting for updates. More rooms ready for guests.</h2><p className="mt-5 text-lg leading-8 text-ink-2">PatelRep connects the small moments that keep a property moving, without asking staff to spend more time staring at a screen.</p></div><div className="mt-12 grid gap-4 lg:grid-cols-3">{workflows.map(({ icon: Icon, eyebrow, title, copy, detail, tone }) => <article key={eyebrow} className="group rounded-2xl border border-line bg-surface p-6 shadow-sm transition duration-200 hover:-translate-y-1 hover:shadow-lg sm:p-7"><span className={`grid size-11 place-items-center rounded-xl border ${tone}`}><Icon className="size-5" aria-hidden="true" /></span><p className="mt-7 font-mono text-[11px] font-semibold uppercase tracking-[0.13em] text-ink-3">{eyebrow}</p><h3 className="mt-3 font-display text-3xl leading-[1.05] tracking-[-0.025em] text-ink">{title}</h3><p className="mt-4 leading-7 text-ink-2">{copy}</p><p className="mt-6 border-t border-line pt-4 text-xs font-semibold text-ink-3">{detail}</p></article>)}</div></section>

    <section className="bg-[#0c6e63] px-6 py-16 text-white sm:px-10 lg:px-12 lg:py-20"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-[1fr_1.08fr] lg:items-center"><div><p className="font-mono text-[11px] font-semibold uppercase tracking-[0.14em] text-[#a4cfc7]">One shift, one source of truth</p><h2 className="mt-4 max-w-lg font-display text-4xl leading-[1.02] tracking-[-0.035em] sm:text-5xl">The handoff gets easier when the whole hotel sees the same thing.</h2></div><div className="grid gap-5 sm:grid-cols-3">{[[Clock3, 'Start clear', 'A shift brief surfaces the rooms and issues that need attention first.'], [BellRing, 'Stay ahead', 'Live updates keep supervisors, front desk, and the floor aligned.'], [Check, 'Finish strong', 'Close the loop with work that is checked, inspected, and recorded.']].map(([Icon, title, copy]) => { const StepIcon = Icon as typeof Clock3; return <div key={title as string} className="border-t border-white/25 pt-4"><StepIcon className="size-5 text-[#b8ded6]" aria-hidden="true" /><h3 className="mt-5 text-base font-semibold">{title as string}</h3><p className="mt-2 text-sm leading-6 text-[#d6eae5]">{copy as string}</p></div> })}</div></div></section>

    <section id="pricing" className="mx-auto max-w-7xl px-6 py-20 sm:px-10 lg:px-12 lg:py-28"><div className="grid gap-10 rounded-3xl border border-line bg-surface-2 p-7 sm:p-10 lg:grid-cols-[1.15fr_0.85fr] lg:p-12"><div><p className="font-mono text-[11px] font-semibold uppercase tracking-[0.14em] text-accent">Straightforward pricing</p><h2 className="mt-4 max-w-xl font-display text-4xl leading-[1.02] tracking-[-0.035em] text-ink sm:text-5xl">A better shift should not require enterprise software.</h2><p className="mt-5 max-w-xl text-lg leading-8 text-ink-2">One practical platform for the hotel teams doing the most time-sensitive work, priced for independent properties.</p></div><div className="rounded-2xl bg-[#1a1815] p-6 text-paper shadow-lg sm:p-7"><p className="font-mono text-[11px] font-semibold uppercase tracking-[0.14em] text-[#f2b59d]">PatelRep</p><p className="mt-5 flex items-baseline gap-1"><span className="font-display text-6xl leading-none">$99</span><span className="text-sm text-[#c5beaf]">/ month</span></p><p className="mt-3 text-sm leading-6 text-[#c5beaf]">Plus $0.02 per AI credit, capped at $2.50 per room each month.</p><Link href="/login" className="mt-7 inline-flex min-h-12 w-full items-center justify-center gap-2 rounded-lg bg-accent px-5 text-sm font-semibold text-white transition hover:bg-[#cb542b]">Start a pilot <ArrowRight className="size-4" aria-hidden="true" /></Link></div></div></section>

    <footer className="border-t border-line px-6 py-7 sm:px-10 lg:px-12"><div className="mx-auto flex max-w-7xl flex-col gap-4 text-sm text-ink-3 sm:flex-row sm:items-center sm:justify-between"><p className="flex items-center gap-2 font-semibold text-ink"><span className="grid size-6 place-items-center rounded-md bg-accent font-mono text-xs text-white">✦</span>PatelRep</p><p>Built for the teams that keep hospitality moving.</p><Link href="/login" className="font-medium text-ink transition hover:text-accent">Staff sign in</Link></div></footer>
  </main>
}
