---
phase: 09-remaining-screens-rollout
plan: 05
type: execute
wave: 2
depends_on: ["01", "02", "03", "04"]
files_modified:
  - apps/mobile/app/(app)/assignments/index.tsx
autonomous: true
requirements: [SCREENS-03]
must_haves:
  truths:
    - "assignments/index.tsx renders hero/list/rows via useTheme() + primitives (zero C. refs)"
    - "The room action-sheet at :238 stays Alert.alert; the lateCo info alert at :361 becomes toast.info"
    - "Reassign/remove-assignment data behavior + RBAC are unchanged (only the feedback call changes)"
  artifacts:
    - path: "apps/mobile/app/(app)/assignments/index.tsx"
      provides: "Assignments screen on primitives"
      contains: "useTheme"
  key_links:
    - from: "apps/mobile/app/(app)/assignments/index.tsx"
      to: "apps/mobile/lib/theme/useToast.ts"
      via: "lateCo info alert → toast.info"
      pattern: "useToast"
---

<objective>
Migrate `assignments/index.tsx` (741 lines — the largest screen in the phase, 52 `C.` refs, 16 `TouchableOpacity`, 2 `Alert.alert`) onto primitives. The room action-sheet at :238 (Reassign / Remove-assignment / Cancel) STAYS `Alert.alert`; the lateCo info alert at :361 converts to `toast.info`. Split into 2 tasks (chrome/list, then rows + alert) for reviewability.

Purpose: SCREENS-03 (assignments) — supervisor reassigns/removes on primitives; data/RBAC unchanged.
Output: `assignments/index.tsx` on primitives, zero `C.` refs, action-sheet intact, lateCo → toast.
</objective>

<execution_context>
@$HOME/.claude/get-shit-done/workflows/execute-plan.md
@$HOME/.claude/get-shit-done/templates/summary.md
</execution_context>

<context>
@.planning/PROJECT.md
@.planning/ROADMAP.md
@.planning/STATE.md
@.planning/phases/09-remaining-screens-rollout/09-CONTEXT.md
@.planning/phases/09-remaining-screens-rollout/09-PATTERNS.md
@.planning/phases/08-floor-role-rollout/08-PATTERNS.md

<migration_reference>
## C.* → theme.* map (from 08-PATTERNS.md — name changes matter):
C.paper→theme.background  C.ink→theme.textPrimary  C.ink2→theme.textSecondary  C.ink3→theme.textMuted
C.ink4→theme.textDisabled  C.surface→theme.surface  C.surface2→theme.surfaceSubtle  C.surface3→theme.surfaceMuted
C.line→theme.border  C.line2→theme.borderSubtle  C.accent→theme.primaryAction  C.accentSoft→theme.primarySoft
C.accentLine→theme.primaryLine  C.brass→theme.accentBrass  C.brassSoft→theme.accentBrassSoft  C.brassLine→theme.accentBrassLine
C.ready→theme.status.ready  C.caution→theme.status.pickup  C.alert→theme.status.dirty  C.info→theme.status.clean  C.ooo→theme.status.outOfOrder
shellTokens.* / C.shell*→theme.shell.*  (caution→pickup, alert→dirty, info→clean, ooo→outOfOrder)

## Imports: `import { useTheme } from "@/lib/theme/useTheme"; const theme = useTheme();`
##          `import { useToast } from "@/lib/theme/useToast"; const toast = useToast();`
## Toast contract: toast.success/error/info(msg) — msg is already-translated (caller owns t()).
## D-10 classification (verified): assignments:238 STAYS Alert.alert (multi-way action sheet); assignments:361 lateCo → toast.info.
## Pitfall 3: handlers mix real api.* / reassign logic with the alert — change ONLY the feedback call; never touch preceding awaited calls, early-return guards, or tenant-scoping args.
## Card has NO onPress → Pressable wraps Card; StateBlock loading/empty/error; RefreshControl tintColor={theme.primaryAction}.
</migration_reference>
</context>

<tasks>

<task type="auto">
  <name>Task 1: Migrate assignments hero + list chrome + StateBlock</name>
  <files>apps/mobile/app/(app)/assignments/index.tsx</files>
  <read_first>
    - apps/mobile/app/(app)/assignments/index.tsx (full — 741 lines, 52 C. refs; hero chrome, filter/segment controls, loading/empty/error blocks, list container)
    - apps/mobile/app/(app)/work-orders/index.tsx (Phase-8 hero/StateBlock exemplar)
    - apps/mobile/components/ui/StateBlock.tsx
  </read_first>
  <action>
    1. Add `import { useTheme } from "@/lib/theme/useTheme"; const theme = useTheme();`.
    2. Migrate the hero, segment/filter controls, and container chrome: replace `C.*` with `theme.*` per map; route dark hero + `shellTokens`/`C.shell*` to `theme.shell.*`. Keep StyleSheet; color objects LAST.
    3. Convert loading/empty/error blocks to `<StateBlock status="loading|empty|error" ... />` reusing existing `t(...)` keys; if any block passes `onRetry`, add the required `retryLabel`. `RefreshControl tintColor={theme.primaryAction}`.
    4. Leave the row-card rendering and both `Alert.alert` handlers for Task 2. Do NOT change fetch/filter/RBAC logic.
  </action>
  <verify>
    <automated>cd apps/mobile && npm run type-check && npm run lint</automated>
  </verify>
  <acceptance_criteria>
    - `@('useTheme', 'StateBlock') | ForEach-Object { if (@(Select-String -LiteralPath 'apps/mobile/app/(app)/assignments/index.tsx' -SimpleMatch $_ -ErrorAction Stop).Count -lt 1) { exit 1 } }` exits 0
    - `if (@(Select-String -LiteralPath 'apps/mobile/app/(app)/assignments/index.tsx' -SimpleMatch 'shellTokens' -ErrorAction Stop).Count -ne 0) { exit 1 }` exits 0
    - `npm run type-check` + `npm run lint` green
    - Diff review: no fetch/filter/RBAC logic changed
  </acceptance_criteria>
  <done>Assignments hero/list chrome + state blocks on primitives; type-check + lint green; row/alert work deferred to Task 2.</done>
</task>

<task type="auto">
  <name>Task 2: Migrate assignment rows + finish C. burn-down + alert reclassification</name>
  <files>apps/mobile/app/(app)/assignments/index.tsx</files>
  <read_first>
    - apps/mobile/app/(app)/assignments/index.tsx (rows/cards region + Alert.alert at :238 and :361; the reassign/remove handler bodies)
    - apps/mobile/components/engineering/WorkOrderCard.tsx (Pressable-wraps-Card, StatusBadge)
    - apps/mobile/lib/theme/useToast.ts
  </read_first>
  <action>
    1. Add `import { useToast } from "@/lib/theme/useToast"; const toast = useToast();`.
    2. Rebuild each tappable assignment row (currently a single `TouchableOpacity`) as `<Pressable onPress={...}><Card style={[styles.cardLayoutOverrides]}>…</Card></Pressable>`, re-applying asymmetric padding via style. Convert StatusKey-matching chips (room status, pickup) to `<StatusBadge statusKey=... label={t(...)} />`; non-matching chips color-migrated only.
    3. Replace ALL remaining `C.*` refs with `theme.*` per map so the file reaches zero.
    4. Alerts (D-10): LEAVE `Alert.alert` at :238 (Reassign / Remove-assignment / Cancel action sheet — a multi-way choice) unchanged. Convert :361 lateCo info (title+body, no buttons) to `toast.info(msg)` using the existing translated string. Change ONLY the feedback call at :361 — do NOT touch the preceding `await api.*` reassign/remove calls, early-return guards, or `hotel_id`/tenant args in either handler.
  </action>
  <verify>
    <automated>cd apps/mobile && npm run type-check && npm run lint</automated>
  </verify>
  <acceptance_criteria>
    - Zero C. refs: `if (@(Select-String -LiteralPath 'apps/mobile/app/(app)/assignments/index.tsx' -Pattern '\bC\.[a-zA-Z]' -ErrorAction Stop).Count -ne 0) { exit 1 }` exits 0
    - Action sheet intact: `if (@(Select-String -LiteralPath 'apps/mobile/app/(app)/assignments/index.tsx' -SimpleMatch 'Alert.alert' -ErrorAction Stop).Count -ne 1) { exit 1 }` exits 0 (only the :238 sheet)
    - `@('useToast', '<Card', 'Pressable') | ForEach-Object { if (@(Select-String -LiteralPath 'apps/mobile/app/(app)/assignments/index.tsx' -SimpleMatch $_ -ErrorAction Stop).Count -lt 1) { exit 1 } }` exits 0
    - `npm run type-check` + `npm run lint` green
    - Diff review: reassign/remove `api.*` calls + guards + tenant args unchanged
  </acceptance_criteria>
  <done>Assignments fully on primitives, zero C. refs, :238 sheet stays blocking, :361 lateCo is toast.info, reassign/remove logic untouched, type-check + lint green.</done>
</task>

</tasks>

<threat_model>
## Trust Boundaries

| Boundary | Description |
|----------|-------------|
| device → API (reassign / remove-assignment, hotel_id-scoped) | Supervisor-role-gated mutations; NOT modified — only the feedback call at :361 changes. |

## STRIDE Threat Register

| Threat ID | Category | Component | Disposition | Mitigation Plan |
|-----------|----------|-----------|-------------|-----------------|
| T-09-05-01 | Elevation of Privilege / Information Disclosure | Converting the :361 alert accidentally drops the reassign/remove `await api.*` call, its early-return guard, or the `hotel_id` scoping in the same handler | mitigate | Pitfall-3 rule: change ONLY the feedback call; diff review asserts api/guard/tenant args unchanged |
| T-09-05-02 | Tampering | The :238 multi-way action sheet is converted to Toast, losing the Reassign/Remove choice gate | mitigate | D-10: :238 stays Alert.alert; acceptance criteria assert exactly 1 Alert.alert remains |
| T-09-05-03 | Tampering | Row Card rebuild drops `onPress`, making assignment rows non-interactive | mitigate | Pressable-wraps-Card mandated; grep asserts Pressable + Card |
</threat_model>

<verification>
- `cd apps/mobile && npm run type-check && npm run lint` green
- `if (@(Select-String -LiteralPath 'apps/mobile/app/(app)/assignments/index.tsx' -Pattern '\bC\.[a-zA-Z]' -ErrorAction Stop).Count -ne 0) { exit 1 }`
- `if (@(Select-String -LiteralPath 'apps/mobile/app/(app)/assignments/index.tsx' -SimpleMatch 'Alert.alert' -ErrorAction Stop).Count -ne 1) { exit 1 }`
</verification>

<success_criteria>
SCREENS-03 (assignments): supervisor reassigns/removes on primitives; :238 action sheet stays blocking; :361 lateCo is toast.info; data/RBAC unchanged; zero legacy C tokens.
</success_criteria>

<output>
After completion, create `.planning/phases/09-remaining-screens-rollout/09-05-SUMMARY.md`.
</output>
