"""Metric definition registry — the ONE place business definitions are written down.

Served to the web app by ``GET /v1/reports/definitions`` (KPI drawer, tooltips)
and embedded in PDF/CSV exports. Each entry must match the implementation in
``metrics.py`` / the report builders; ``higher_is_better`` drives
favorable/unfavorable colouring (None = no polarity).
"""
from __future__ import annotations

from typing import Optional

_PERIOD = "period"
_LIVE = "live"
_FORECAST = "forecast"

DEFINITIONS: dict[str, dict] = {
    "guest_sla": {
        "label": "Guest SLA Compliance",
        "unit": "percent",
        "higher_is_better": True,
        "scope": _PERIOD,
        "definition": "Share of SLA-eligible guest requests that were verified resolved by their deadline.",
        "numerator": "Requests verified on or before their due time.",
        "denominator": "Requests created in the period that have a due time AND are either verified or already past due (cancelled and still-running requests inside their window are excluded).",
        "cohort": "Guest requests created in the selected period (hotel-local days).",
        "exclusions": "Requests without a due time; cancelled requests; open requests whose deadline has not yet passed.",
        "source": "guest_requests (created_at, due_at, verified_at, status)",
    },
    "guest_verified_resolution": {
        "label": "Verified Resolution Rate",
        "unit": "percent",
        "higher_is_better": True,
        "scope": _PERIOD,
        "definition": "Share of guest requests created in the period that have been verified resolved.",
        "numerator": "Requests with status verified.",
        "denominator": "All guest requests created in the period.",
        "cohort": "Guest requests created in the selected period.",
        "exclusions": "None.",
        "source": "guest_requests (status, verified_at)",
    },
    "guest_ack_time": {
        "label": "Average Acknowledgement Time",
        "unit": "minutes",
        "higher_is_better": False,
        "scope": _PERIOD,
        "definition": "Mean minutes from request creation to first acknowledgement.",
        "numerator": "Sum of (acknowledged_at - created_at).",
        "denominator": "Requests with an acknowledgement timestamp.",
        "cohort": "Guest requests created in the selected period.",
        "exclusions": "Requests never acknowledged.",
        "source": "guest_requests (created_at, acknowledged_at)",
    },
    "guest_resolution_time": {
        "label": "Average Verified Resolution Time",
        "unit": "minutes",
        "higher_is_better": False,
        "scope": _PERIOD,
        "definition": "Mean minutes from request creation to verified resolution.",
        "numerator": "Sum of (verified_at - created_at).",
        "denominator": "Verified requests.",
        "cohort": "Guest requests created in the selected period.",
        "exclusions": "Requests not yet verified.",
        "source": "guest_requests (created_at, verified_at)",
    },
    "guest_requests_total": {
        "label": "Guest Requests Received",
        "unit": "count",
        "higher_is_better": None,
        "scope": _PERIOD,
        "definition": "Number of guest requests created in the period.",
        "numerator": "Count of requests.",
        "denominator": "—",
        "cohort": "Guest requests created in the selected period.",
        "exclusions": "None.",
        "source": "guest_requests",
    },
    "maintenance_sla": {
        "label": "Maintenance SLA Compliance",
        "unit": "percent",
        "higher_is_better": True,
        "scope": _PERIOD,
        "definition": "Share of SLA-eligible completed work orders finished by their due time.",
        "numerator": "Completed work orders with completed_at on or before due_at.",
        "denominator": "Completed work orders in the cohort that have both a due time and a completion time.",
        "cohort": "Work orders created in the selected period (hotel-local days).",
        "exclusions": "Work orders without a due time; work orders not yet completed (see Active SLA Breaches for open overdue work).",
        "source": "work_orders (created_at, due_at, completed_at, status)",
    },
    "maintenance_response": {
        "label": "Average Response Time",
        "unit": "hours",
        "higher_is_better": False,
        "scope": _PERIOD,
        "definition": "Mean hours from work order creation to work starting.",
        "numerator": "Sum of (started_at - created_at).",
        "denominator": "Work orders with a start timestamp.",
        "cohort": "Work orders created in the selected period.",
        "exclusions": "Work orders never started.",
        "source": "work_orders (created_at, started_at)",
    },
    "maintenance_repair": {
        "label": "Average Repair Time",
        "unit": "hours",
        "higher_is_better": False,
        "scope": _PERIOD,
        "definition": "Mean hours from work starting to completion.",
        "numerator": "Sum of (completed_at - started_at).",
        "denominator": "Completed work orders with both timestamps.",
        "cohort": "Work orders created in the selected period.",
        "exclusions": "Work orders without a start or completion time.",
        "source": "work_orders (started_at, completed_at)",
    },
    "maintenance_completion": {
        "label": "Work Order Completion Rate",
        "unit": "percent",
        "higher_is_better": True,
        "scope": _PERIOD,
        "definition": "Share of work orders created in the period that are completed.",
        "numerator": "Completed work orders.",
        "denominator": "All work orders created in the period.",
        "cohort": "Work orders created in the selected period.",
        "exclusions": "None (cancelled work orders count in the denominator).",
        "source": "work_orders (status)",
    },
    "active_sla_breaches": {
        "label": "Active SLA Breaches",
        "unit": "count",
        "higher_is_better": False,
        "scope": _LIVE,
        "definition": "Open, in-progress or on-hold work orders whose due time has passed right now.",
        "numerator": "Count of overdue open work orders.",
        "denominator": "—",
        "cohort": "ALL currently open work orders, regardless of when they were created. Not limited to the selected period.",
        "exclusions": "Work orders without a due time.",
        "source": "work_orders (status, due_at)",
    },
    "inspection_pass": {
        "label": "Inspection Pass Rate",
        "unit": "percent",
        "higher_is_better": True,
        "scope": _PERIOD,
        "definition": "Share of completed room inspections with an overall result of passed. Conditional is not a pass.",
        "numerator": "Inspections with overall_result = passed.",
        "denominator": "Inspections completed in the period.",
        "cohort": "Inspections completed in the selected period.",
        "exclusions": "Inspections not completed.",
        "source": "inspections (overall_result, completed_at)",
    },
    "out_of_order": {
        "label": "Out-of-Order Rooms (now)",
        "unit": "count",
        "higher_is_better": False,
        "scope": _LIVE,
        "definition": "Rooms currently in Out-of-Order / Out-of-Service status. This is a live operational count, not a historical figure, and not PMS occupancy.",
        "numerator": "Rooms whose current status is OOO.",
        "denominator": "—",
        "cohort": "Current room status board.",
        "exclusions": "No historical comparison exists (no daily status snapshots are stored).",
        "source": "room_status (status)",
    },
    "rooms_serviced": {
        "label": "Rooms Serviced",
        "unit": "count",
        "higher_is_better": None,
        "scope": _PERIOD,
        "definition": "Completed cleaning sessions (a room moving IN_PROGRESS to CLEAN/INSPECTED) in the period.",
        "numerator": "Count of clean sessions.",
        "denominator": "—",
        "cohort": "Clean sessions that ended in the selected period.",
        "exclusions": "Sessions that never closed within the available status history.",
        "source": "room_status_history",
    },
    "cleaning_minutes": {
        "label": "Average Cleaning Minutes per Occupied Room",
        "unit": "minutes",
        "higher_is_better": False,
        "scope": _PERIOD,
        "definition": "Mean minutes of clean sessions (room IN_PROGRESS until CLEAN/INSPECTED).",
        "numerator": "Sum of session minutes.",
        "denominator": "Clean sessions.",
        "cohort": "Clean sessions that ended in the selected period.",
        "exclusions": "Sessions without both transitions in the available history. Baselines are shown only where configured on the room type.",
        "source": "room_status_history, room_types.base_clean_minutes",
    },
    "repeat_defects": {
        "label": "Repeat Inspection Defects",
        "unit": "count",
        "higher_is_better": False,
        "scope": _PERIOD,
        "definition": "Checklist items that failed in 2 or more inspections in the period. This measures repeat defects, not re-cleans.",
        "numerator": "Count of checklist items failing in 2+ inspections.",
        "denominator": "—",
        "cohort": "Inspections completed in the selected period.",
        "exclusions": "Re-clean events are not separately recorded.",
        "source": "inspection_results",
    },
    "pm_compliance": {
        "label": "PM Compliance Rate",
        "unit": "percent",
        "higher_is_better": True,
        "scope": _PERIOD,
        "definition": "Preventive-maintenance completions relative to completions plus deferrals in the period.",
        "numerator": "PM completion records.",
        "denominator": "PM completion records + PM deferrals.",
        "cohort": "Records created in the selected period.",
        "exclusions": "Inactive schedules.",
        "source": "pm_completion_records, pm_deferrals",
    },
    "tasks_completed": {
        "label": "Tasks Completed",
        "unit": "count",
        "higher_is_better": None,
        "scope": _PERIOD,
        "definition": "Tasks created in the period that are completed.",
        "numerator": "Completed tasks.",
        "denominator": "—",
        "cohort": "Tasks created in the selected period assigned to visible staff.",
        "exclusions": "Unassigned tasks.",
        "source": "tasks (status, assigned_to)",
    },
    "wo_completed": {
        "label": "Work Orders Completed",
        "unit": "count",
        "higher_is_better": None,
        "scope": _PERIOD,
        "definition": "Work orders created in the period that are completed.",
        "numerator": "Completed work orders.",
        "denominator": "—",
        "cohort": "Work orders created in the selected period assigned to visible staff.",
        "exclusions": "Unassigned work orders.",
        "source": "work_orders (status, assigned_to)",
    },
    "team_sla": {
        "label": "Eligible SLA Compliance",
        "unit": "percent",
        "higher_is_better": True,
        "scope": _PERIOD,
        "definition": "Share of completed, deadline-bearing tasks and work orders finished on time.",
        "numerator": "Completed items with completed_at on or before due_at.",
        "denominator": "Completed tasks and work orders that have both a due time and a completion time.",
        "cohort": "Tasks and work orders created in the period and assigned to visible staff.",
        "exclusions": "Items without a due time. Complexity and workload differ by role, so compare within a department only.",
        "source": "tasks, work_orders",
    },
    "labor_hours": {
        "label": "Recorded Labor Hours",
        "unit": "hours",
        "higher_is_better": None,
        "scope": _PERIOD,
        "definition": "Labor hours logged on completed work orders. Housekeeping task labor is not tracked, so it is excluded rather than counted as zero.",
        "numerator": "Sum of labor_hours.",
        "denominator": "—",
        "cohort": "Completed work orders created in the selected period.",
        "exclusions": "Work orders with no labor recorded; all housekeeping tasks.",
        "source": "work_orders (labor_hours)",
    },
    "downtime_hours": {
        "label": "Room Downtime",
        "unit": "hours",
        "higher_is_better": False,
        "scope": _PERIOD,
        "definition": "Total hours rooms spent in Out-of-Order status inside the period, from recorded status transitions.",
        "numerator": "Sum of OOO intervals clamped to the period.",
        "denominator": "—",
        "cohort": "Room status transitions in the selected period (plus each room's prior state).",
        "exclusions": "Current OOO inventory is NOT treated as historical downtime.",
        "source": "room_status_history",
    },
    "downtime_exposure": {
        "label": "Estimated Downtime Revenue Exposure",
        "unit": "currency",
        "higher_is_better": False,
        "scope": _PERIOD,
        "definition": "ESTIMATE: room downtime hours multiplied by the hotel's configured ADR / 24. It is an exposure estimate, not actual lost revenue.",
        "numerator": "Downtime hours x (ADR / 24).",
        "denominator": "—",
        "cohort": "As Room Downtime.",
        "exclusions": "Unavailable until the GM configures ADR in Settings.",
        "source": "room_status_history, tenants.average_daily_rate_cents",
    },
}


def definition_for(key: str) -> Optional[dict]:
    return DEFINITIONS.get(key)


def higher_is_better(key: str) -> Optional[bool]:
    entry = DEFINITIONS.get(key)
    return entry.get("higher_is_better") if entry else None
