/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/copilot` | `/copilot`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/my-rooms` | `/my-rooms`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/tasks` | `/tasks`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/work-orders` | `/work-orders`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/auth/callback` | `/auth/callback`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/my-rooms/[roomId]` | `/my-rooms/[roomId]`, params: Router.UnknownInputParams & { roomId: string | number; } } | { pathname: `${'/(app)'}/work-orders/[woId]` | `/work-orders/[woId]`, params: Router.UnknownInputParams & { woId: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/copilot` | `/copilot`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/my-rooms` | `/my-rooms`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/tasks` | `/tasks`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/work-orders` | `/work-orders`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/auth/callback` | `/auth/callback`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/my-rooms/[roomId]` | `/my-rooms/[roomId]`, params: Router.UnknownOutputParams & { roomId: string; } } | { pathname: `${'/(app)'}/work-orders/[woId]` | `/work-orders/[woId]`, params: Router.UnknownOutputParams & { woId: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/copilot${`?${string}` | `#${string}` | ''}` | `/copilot${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/my-rooms${`?${string}` | `#${string}` | ''}` | `/my-rooms${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/tasks${`?${string}` | `#${string}` | ''}` | `/tasks${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/work-orders${`?${string}` | `#${string}` | ''}` | `/work-orders${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/auth/callback${`?${string}` | `#${string}` | ''}` | `/auth/callback${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/copilot` | `/copilot`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/my-rooms` | `/my-rooms`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/tasks` | `/tasks`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/work-orders` | `/work-orders`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/auth/callback` | `/auth/callback`; params?: Router.UnknownInputParams; } | `${'/(app)'}/my-rooms/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/my-rooms/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/work-orders/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/work-orders/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `${'/(app)'}/my-rooms/[roomId]` | `/my-rooms/[roomId]`, params: Router.UnknownInputParams & { roomId: string | number; } } | { pathname: `${'/(app)'}/work-orders/[woId]` | `/work-orders/[woId]`, params: Router.UnknownInputParams & { woId: string | number; } };
    }
  }
}
