-- =============================================================================
-- Migration 007: Work Orders
-- Engineering maintenance work order system with photo documentation
-- =============================================================================

-- ---------------------------------------------------------------------------
-- work_orders
-- Engineering and facilities maintenance work orders. Supports both
-- reactive (staff/AI created) and preventive maintenance (PM generated).
-- asset_id and pm_schedule_id FKs are added in migration 008 after those
-- tables are created.
-- ---------------------------------------------------------------------------
CREATE TABLE work_orders (
  id                  UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id           UUID        NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  work_order_number   SERIAL,                              -- human-readable sequential WO number

  title               TEXT        NOT NULL,
  description         TEXT,
  original_nl_input   TEXT,                               -- raw NL input when AI-created

  category            TEXT        NOT NULL CHECK (category IN (
                        'plumbing',
                        'electrical',
                        'hvac',
                        'furniture',
                        'appliance',
                        'structural',
                        'safety',
                        'general'
                      )),

  priority            TEXT        NOT NULL DEFAULT 'normal' CHECK (priority IN (
                        'urgent',   -- safety issue or VIP impact
                        'normal',
                        'low'
                      )),

  status              TEXT        NOT NULL DEFAULT 'open' CHECK (status IN (
                        'open',
                        'in_progress',
                        'on_hold',      -- awaiting parts or approval
                        'completed',
                        'cancelled'
                      )),

  -- Location
  room_id             UUID        REFERENCES rooms(id) ON DELETE SET NULL,
  location_text       TEXT,

  -- Asset linkage (FK added in 008_assets_pm.sql)
  asset_id            UUID,

  -- Assignment
  assigned_to         UUID        REFERENCES auth.users(id) ON DELETE SET NULL,
  created_by          UUID        NOT NULL REFERENCES auth.users(id),

  -- AI metadata
  is_ai_created       BOOLEAN     NOT NULL DEFAULT FALSE,
  is_pm_generated     BOOLEAN     NOT NULL DEFAULT FALSE,  -- true if auto-generated by PM scheduler

  -- PM linkage (FK added in 008_assets_pm.sql)
  pm_schedule_id      UUID,

  -- SLA tracking
  sla_minutes         INT         NOT NULL DEFAULT 240,    -- 4-hour default SLA
  due_at              TIMESTAMPTZ,

  -- Lifecycle
  started_at          TIMESTAMPTZ,
  completed_at        TIMESTAMPTZ,

  -- Completion details
  parts_used          TEXT,                               -- free-text parts/materials used
  labor_hours         DECIMAL(4,2),
  notes               TEXT,

  created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE work_orders IS 'Engineering maintenance work orders. Covers reactive and preventive maintenance.';
COMMENT ON COLUMN work_orders.work_order_number IS 'Auto-incrementing human-readable WO number per tenant.';
COMMENT ON COLUMN work_orders.is_pm_generated IS 'True when work order was auto-generated by a PM schedule trigger.';
COMMENT ON COLUMN work_orders.original_nl_input IS 'Raw natural language text when work order was created via AI.';

-- ---------------------------------------------------------------------------
-- work_order_photos
-- Before/after/progress photos attached to work orders. Stored in Supabase
-- Storage; this table holds metadata and the storage path reference.
-- ---------------------------------------------------------------------------
CREATE TABLE work_order_photos (
  id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  work_order_id   UUID        NOT NULL REFERENCES work_orders(id) ON DELETE CASCADE,
  tenant_id       UUID        NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  uploaded_by     UUID        NOT NULL REFERENCES auth.users(id),
  storage_path    TEXT        NOT NULL,                   -- Supabase Storage object path
  photo_type      TEXT        NOT NULL DEFAULT 'progress' CHECK (photo_type IN (
                    'before',
                    'after',
                    'progress'
                  )),
  caption         TEXT,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE work_order_photos IS 'Photo documentation for work orders. References Supabase Storage objects.';
COMMENT ON COLUMN work_order_photos.storage_path IS 'Supabase Storage path, e.g. "work-orders/{tenant_id}/{wo_id}/{filename}".';

-- ---------------------------------------------------------------------------
-- work_order_comments
-- Engineer notes, status updates, and system messages on a work order.
-- ---------------------------------------------------------------------------
CREATE TABLE work_order_comments (
  id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  work_order_id   UUID        NOT NULL REFERENCES work_orders(id) ON DELETE CASCADE,
  tenant_id       UUID        NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  user_id         UUID        NOT NULL REFERENCES auth.users(id),
  comment         TEXT        NOT NULL,
  is_system       BOOLEAN     NOT NULL DEFAULT FALSE,     -- true for automated system messages
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE work_order_comments IS 'Comments and system events on work orders. Cascade-deleted with parent.';
