-- =============================================================================
-- Migration 012: Logbook & Shift Summaries
-- Digital shift logbook entries and AI-generated shift summary reports
-- =============================================================================

-- ---------------------------------------------------------------------------
-- logbook_entries
-- Digital shift log replacing paper logbooks. Entries can be manually written
-- by supervisors or auto-generated by the AI shift summary engine.
-- ---------------------------------------------------------------------------
CREATE TABLE logbook_entries (
  id               UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id        UUID        NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  department_id    UUID        NOT NULL REFERENCES departments(id) ON DELETE CASCADE,
  shift_id         UUID        REFERENCES shifts(id) ON DELETE SET NULL,
  entry_date       DATE        NOT NULL DEFAULT CURRENT_DATE,
  content          TEXT        NOT NULL,            -- the log entry body text
  is_ai_generated  BOOLEAN     NOT NULL DEFAULT FALSE,  -- true when AI drafted the entry
  author_id        UUID        REFERENCES auth.users(id) ON DELETE SET NULL,  -- NULL for pure AI entries
  created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE logbook_entries IS 'Digital shift logbook. Replaces paper logs; entries can be human or AI-authored.';
COMMENT ON COLUMN logbook_entries.is_ai_generated IS 'True when the AI shift summary engine generated this entry.';
COMMENT ON COLUMN logbook_entries.author_id IS 'NULL for fully AI-generated entries; set to staff member for human or AI-assisted entries.';

-- ---------------------------------------------------------------------------
-- shift_summaries
-- AI-generated end-of-shift summary reports. Aggregates task completions,
-- work order status, room metrics, and notable incidents for the shift.
-- Stored alongside the raw stats JSON for structured reporting.
-- ---------------------------------------------------------------------------
CREATE TABLE shift_summaries (
  id             UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id      UUID        NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  shift_id       UUID        NOT NULL REFERENCES shifts(id) ON DELETE CASCADE,
  shift_date     DATE        NOT NULL,
  department_id  UUID        NOT NULL REFERENCES departments(id) ON DELETE CASCADE,
  summary_text   TEXT        NOT NULL,                 -- AI-generated narrative summary
  stats          JSONB       NOT NULL DEFAULT '{}',    -- structured metrics snapshot
  generated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE shift_summaries IS 'AI-generated shift summary reports with narrative text and structured metrics.';
COMMENT ON COLUMN shift_summaries.summary_text IS 'AI-generated narrative summary for GM review and GM Dashboard display.';
COMMENT ON COLUMN shift_summaries.stats IS
  'Structured metrics JSON. Example keys: tasks_completed, tasks_open, rooms_cleaned, '
  'rooms_inspected, work_orders_closed, average_task_completion_minutes.';
