ALTER TABLE room_status
  ADD COLUMN IF NOT EXISTS stripped        BOOLEAN   NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS stripped_by     UUID,
  ADD COLUMN IF NOT EXISTS stripped_at     TIMESTAMPTZ;
