-- Lost & Found Phase 3: guest missing-item claims and human-verified recovery matches.
-- A match records ownership review only; a found item remains physically held until Phase 4 release.

CREATE TABLE IF NOT EXISTS public.lost_found_claims (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
  claim_number BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  guest_name TEXT NOT NULL,
  guest_phone TEXT,
  guest_email TEXT,
  room_id UUID REFERENCES public.rooms(id) ON DELETE SET NULL,
  room_number TEXT,
  stay_start DATE,
  stay_end DATE,
  description TEXT NOT NULL,
  category TEXT NOT NULL DEFAULT 'other',
  distinguishing_details TEXT,
  last_seen_at TIMESTAMPTZ,
  notes TEXT,
  status TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'matched', 'closed', 'cancelled')),
  matched_item_id UUID REFERENCES public.lost_found_items(id) ON DELETE SET NULL,
  matched_at TIMESTAMPTZ,
  matched_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  verification_notes TEXT,
  cancelled_at TIMESTAMPTZ,
  cancelled_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  cancellation_reason TEXT,
  created_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT lost_found_claims_category_check CHECK (category IN (
    'electronics', 'clothing', 'jewelry', 'bags_luggage', 'keys',
    'wallets_cards', 'documents', 'medical', 'toiletries', 'accessories', 'other'
  )),
  CONSTRAINT lost_found_claims_stay_dates_check CHECK (stay_end IS NULL OR stay_start IS NULL OR stay_end >= stay_start),
  CONSTRAINT lost_found_claims_match_state_check CHECK (
    (status = 'matched' AND matched_item_id IS NOT NULL AND matched_at IS NOT NULL AND verification_notes IS NOT NULL)
    OR status <> 'matched'
  ),
  UNIQUE (tenant_id, claim_number)
);

CREATE TABLE IF NOT EXISTS public.lost_found_claim_events (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
  claim_id UUID NOT NULL REFERENCES public.lost_found_claims(id) ON DELETE CASCADE,
  item_id UUID REFERENCES public.lost_found_items(id) ON DELETE SET NULL,
  event_type TEXT NOT NULL CHECK (event_type IN ('created', 'updated', 'possible_match_reviewed', 'match_confirmed', 'match_removed', 'cancelled')),
  actor_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  note TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.lost_found_match_rejections (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
  claim_id UUID NOT NULL REFERENCES public.lost_found_claims(id) ON DELETE CASCADE,
  item_id UUID NOT NULL REFERENCES public.lost_found_items(id) ON DELETE CASCADE,
  rejected_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  reason TEXT,
  rejected_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (claim_id, item_id)
);

-- This partial unique index is the final concurrency guard: no two active
-- claims can confirm the same item even if their reviews race in separate tabs.
CREATE UNIQUE INDEX IF NOT EXISTS idx_lost_found_one_confirmed_claim_per_item
  ON public.lost_found_claims (tenant_id, matched_item_id)
  WHERE status = 'matched' AND matched_item_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_lost_found_claims_tenant_status_created
  ON public.lost_found_claims (tenant_id, status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_lost_found_claims_tenant_room
  ON public.lost_found_claims (tenant_id, room_id);
CREATE INDEX IF NOT EXISTS idx_lost_found_claim_events_history
  ON public.lost_found_claim_events (tenant_id, claim_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_lost_found_match_rejections_claim
  ON public.lost_found_match_rejections (tenant_id, claim_id, item_id);

ALTER TABLE public.lost_found_claims ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.lost_found_claim_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.lost_found_match_rejections ENABLE ROW LEVEL SECURITY;

CREATE POLICY "tenant_lost_found_claims" ON public.lost_found_claims FOR ALL
  USING (tenant_id = ((SELECT auth.jwt()) ->> 'hotel_id')::uuid);
CREATE POLICY "tenant_lost_found_claim_events" ON public.lost_found_claim_events FOR ALL
  USING (tenant_id = ((SELECT auth.jwt()) ->> 'hotel_id')::uuid);
CREATE POLICY "tenant_lost_found_match_rejections" ON public.lost_found_match_rejections FOR ALL
  USING (tenant_id = ((SELECT auth.jwt()) ->> 'hotel_id')::uuid);
