import React from "react";
import { render, waitFor, within } from "@testing-library/react-native";

const mockSetMyRooms = jest.fn();

const mockRooms = [
  {
    id: "room-108",
    room_number: "108",
    floor: 1,
    status: "IN_PROGRESS",
    risk_level: null,
    dnd_flag: false,
    guest_name: "Guest still in",
    predicted_ready_at: null,
    vip_flag: false,
    checkin_time: null,
  },
  {
    id: "room-112",
    room_number: "112",
    floor: 1,
    status: "DIRTY",
    risk_level: null,
    dnd_flag: false,
    guest_name: null,
    predicted_ready_at: null,
    vip_flag: false,
    checkin_time: null,
  },
  {
    id: "room-115",
    room_number: "115",
    floor: 1,
    status: "DIRTY",
    risk_level: "HIGH",
    dnd_flag: false,
    guest_name: "Mr. Bell",
    predicted_ready_at: null,
    vip_flag: true,
    checkin_time: "2026-05-26T15:00:00.000Z",
  },
  {
    id: "room-101",
    room_number: "101",
    floor: 1,
    status: "INSPECTED",
    risk_level: null,
    dnd_flag: false,
    guest_name: null,
    predicted_ready_at: null,
    vip_flag: false,
    checkin_time: null,
  },
];

const EN: Record<string, string> = {
  "home.greetingMorning": "Good morning, {{name}}.",
  "home.greetingAfternoon": "Good afternoon, {{name}}.",
  "home.greetingEvening": "Good evening, {{name}}.",
  "home.shiftSuffix": "Day shift",
  "home.heroProgress": "{{done}} of {{total}} rooms done",
  "home.glance": "Your shift at a glance",
  "home.openMyRooms": "Open My Rooms",
  "home.stat.timeLeft": "Est. cleaning left",
  "home.stat.finishBy": "On track to finish",
  "home.stat.vipsLeft": "VIPs still ahead",
  "home.stat.review": "Waiting on review",
  "home.companion.kicker": "With you",
  "home.companion.empty": "Nothing on your board yet. Enjoy the calm — your rooms will appear here.",
  "home.companion.fresh": "One room at a time — that's all today is.",
  "home.companion.early": "{{done}} done already. You're finding your rhythm.",
  "home.companion.mid": "{{done}} of {{total}} handled — past the halfway feeling. Steady does it.",
  "home.companion.late": "Home stretch. Just {{count}} to go — you've got this.",
  "home.companion.done": "That's a wrap — every room handled. Be proud of today.",
  "home.companion.tipAttention": "{{count}} room(s) are waiting on review — that's not on you. Flag it and keep moving.",
  "home.companion.tipDnd": "DND is up on {{count}} room(s). Skip them guilt-free — they'll clear.",
  "home.companion.tipArrivals": "{{count}} arrival(s) coming up — your plan already puts them first.",
  "home.companion.tipVip": "{{count}} VIP room(s) still ahead — a little extra polish goes a long way.",
  "home.companion.tipBreather": "Good moment for water and a breath. The board can wait two minutes.",
  "home.startWith": "Start with {{room}}",
  "home.askAI": "Ask AI",
  "home.allDone": "All assigned rooms are done.",
  "home.pullToRefresh": "Pull to refresh if your supervisor adds more.",
  "ai.briefing.kicker": "AI Shift Briefing",
  "ai.briefing.planLabel": "Suggested order",
  "ai.briefing.startWith": "Start with room {{room}} — it's the fastest path through your list.",
  "ai.briefing.startVip": "Start with room {{room}} — VIP guest, get it perfect early.",
  "ai.briefing.startArrival": "Start with room {{room}} — the next guest arrives soon.",
  "ai.briefing.allClear": "All caught up. Every assigned room is handled.",
  "ai.briefing.onlyAttentionLeft": "{{count}} room(s) need review before cleaning can start.",
  "ai.briefing.dndWatchout": "Do Not Disturb active on {{count}} room(s) — skip until cleared.",
  "ai.briefing.woWatchout": "Open work orders on {{count}} room(s).",
  "ai.briefing.arrivalWatchout": "Arrivals within 4 hours: {{count}} room(s).",
  "ai.briefing.estTotal": "~{{minutes}} min of cleaning left",
  "ai.briefing.sourceAi": "Generated by AI",
  "ai.briefing.sourceLocal": "Planned on device",
  "ai.briefing.refresh": "New plan",
};

jest.mock("react-i18next", () => ({
  useTranslation: () => ({
    t: (key: string, values?: Record<string, unknown>) => {
      const template = EN[key] ?? key;
      if (!values) return template;
      return template.replace(/\{\{(\w+)\}\}/g, (_, k) => String(values[k] ?? `{{${k}}}`));
    },
  }),
}));

jest.mock("react-native-safe-area-context", () => ({
  useSafeAreaInsets: () => ({ top: 0, right: 0, bottom: 0, left: 0 }),
}));

jest.mock("@expo/vector-icons", () => ({
  Ionicons: () => null,
}));

jest.mock("@/lib/api/client", () => ({
  api: {
    get: jest.fn().mockResolvedValue({ data: mockRooms }),
    post: jest.fn().mockRejectedValue(new Error("ai offline")),
  },
}));

jest.mock("@/lib/offline/db", () => ({
  getRooms: jest.fn().mockResolvedValue(mockRooms),
  upsertRooms: jest.fn().mockResolvedValue(undefined),
}));

jest.mock("@/stores/appStore", () => ({
  useAppStore: () => ({
    user: { id: "user-1", full_name: "Maria Vega", role: "housekeeper" },
    isOnline: true,
    myRooms: mockRooms,
    setMyRooms: mockSetMyRooms,
  }),
}));

import HousekeeperHomeScreen from "@/app/(app)/home";

describe("HousekeeperHomeScreen", () => {
  it("renders the companion hero, AI briefing, and shift analytics — with no up-next room queue", async () => {
    const { getByText, getByTestId, queryByText, queryByTestId } = render(<HousekeeperHomeScreen />);

    // Time-of-day greeting plus the supportive companion check-in
    await waitFor(() => expect(getByText(/Good (morning|afternoon|evening), Maria\./)).toBeTruthy());
    // 1 of 4 done (101 inspected) → "early" stage message
    expect(getByText("1 done already. You're finding your rhythm.")).toBeTruthy();
    expect(getByText("1 of 4 rooms done")).toBeTruthy();
    expect(getByText("25%")).toBeTruthy();

    // AI briefing card with the on-device plan
    expect(getByTestId("ai-briefing-card")).toBeTruthy();
    expect(getByText("AI Shift Briefing")).toBeTruthy();
    // Start CTA picks the first startable room (112), not the in-progress room (108)
    expect(getByText("Start with room 112 — it's the fastest path through your list.")).toBeTruthy();
    expect(getByText("Start with 112")).toBeTruthy();
    expect(getByText("New plan")).toBeTruthy();
    expect(getByText("Ask AI")).toBeTruthy();
    expect(getByText(/Planned on device/)).toBeTruthy();

    // Analytics deck: 108 + 112 cleanable (25m each), 115 needs review (high risk), 1 VIP left
    expect(getByText("Your shift at a glance")).toBeTruthy();
    expect(getByText("~50m")).toBeTruthy();
    expect(within(getByTestId("stat-vips")).getByText("1")).toBeTruthy();
    expect(within(getByTestId("stat-review")).getByText("1")).toBeTruthy();

    // Companion tip surfaces the review room as a gentle nudge, not a task
    expect(getByTestId("companion-tip")).toBeTruthy();
    expect(getByText(/waiting on review — that's not on you/)).toBeTruthy();

    // Up Next queue is gone from Home — rooms live in My Rooms
    expect(queryByText("Up next")).toBeNull();
    expect(queryByTestId("room-card-108")).toBeNull();
    expect(queryByTestId("room-card-112")).toBeNull();
    expect(getByText("Open My Rooms")).toBeTruthy();
  });
});
